name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: PHPUnit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml, ctype, iconv, intl

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --testdox
